apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  labels:
    project: Roboshop
    purpose: multi-containers
spec:
  containers:
  - name: nginx
    image: nginx
  
  - name: almalinux
    image: almalinux:9
    # here we will get CrashLoopBackOff error beacuse nginx will run automatically in background using deamon
    # but for almalinux we don't have anything to run by default that why error came
    command: [ "sleep", "1000"]