apiVersion: v1
kind: Pod
metadata:
  name: Multi containers
  labels:
    project: Roboshop
    purpose: multi containers
spec:
  containers:
  - name: nginx
    image: nginx
  
  - name: almalinux
    image: almalinux:9