apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx
  # ReplicaSet labels
  labels:
    purpose: dp-demo
    project: roboshop
    app: nginx

spec:
  replicas: 3

  # ReplicaSet uses these labels to create/manage pods
  # These should match pod template labels
  selector:
    matchLabels:
      purpose: dp-demo
      project: roboshop
      app: nginx

  # Pod definition
  template:
    metadata:
      labels:
        purpose: dp-demo
        project: roboshop
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx